pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - -merged
      - files~=^(!?codes\/)
      - -files~=^(!?.\/)
    actions:
      merge:
        method: merge
      label:
        add:
          - hacktoberfest-accepted
          - good first issue
